#include "completions/cli.h"

#include "generated_scripts.h" // generated by tools/generate_completions_header.py

#include <cstdio>
#include <cstring>
#include <print>

namespace noctalia::completions {
  namespace {

    constexpr const char* kHelpText = "Usage: noctalia completions <shell>\n"
                                      "\n"
                                      "Print a shell completion script to stdout.\n"
                                      "\n"
                                      "Shells:\n"
                                      "  bash\n"
                                      "  zsh\n"
                                      "  fish\n"
                                      "\n"
                                      "Examples:\n"
                                      "  source <(noctalia completions bash)\n"
                                      "  noctalia completions zsh > \"${fpath[1]}/_noctalia\"\n"
                                      "  noctalia completions fish > ~/.config/fish/completions/noctalia.fish\n";

  } // namespace

  int runCli(int argc, char* argv[]) {
    if (argc < 3 || std::strcmp(argv[2], "--help") == 0) {
      std::println("{}", kHelpText);
      return argc < 3 ? 1 : 0;
    }

    if (argc > 3) {
      std::println(stderr, "error: unexpected argument: {}", argv[3]);
      std::println(stderr, "Run 'noctalia completions --help' for usage.");
      return 1;
    }

    const char* shell = argv[2];
    std::string_view script;
    if (std::strcmp(shell, "bash") == 0) {
      script = kBashScript;
    } else if (std::strcmp(shell, "zsh") == 0) {
      script = kZshScript;
    } else if (std::strcmp(shell, "fish") == 0) {
      script = kFishScript;
    } else {
      std::println(stderr, "error: unknown shell: {}", shell);
      std::println(stderr, "Run 'noctalia completions --help' for usage.");
      return 1;
    }

    std::fwrite(script.data(), 1, script.size(), stdout);
    return 0;
  }

} // namespace noctalia::completions
