#!/usr/bin/env python3
"""Embeds assets/completions/*.{bash,zsh,fish} into a generated C++ header.

generate_completions_header.py <output.h> <bash_path> <zsh_path> <fish_path>
"""

import sys


def cpp_raw_string(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        content = f.read()
    # C++ raw string delimiters are capped at 16 characters.
    delim = "NCTLCOMP"
    if f'{delim}(' in content or f'){delim}"' in content:
        raise ValueError(f"delimiter collision in {path}, pick a different delim")
    return f'R"{delim}({content}){delim}"'


def main() -> int:
    if len(sys.argv) != 5:
        print(__doc__, file=sys.stderr)
        return 1

    out_path, bash_path, zsh_path, fish_path = sys.argv[1:5]

    header = f"""// Generated by tools/generate_completions_header.py. Do not edit by hand.
// Edit the source files under assets/completions/ instead.
#pragma once

#include <string_view>

namespace noctalia::completions {{

  inline constexpr std::string_view kBashScript = {cpp_raw_string(bash_path)};
  inline constexpr std::string_view kZshScript = {cpp_raw_string(zsh_path)};
  inline constexpr std::string_view kFishScript = {cpp_raw_string(fish_path)};

}} // namespace noctalia::completions
"""

    with open(out_path, "w", encoding="utf-8") as f:
        f.write(header)

    return 0


if __name__ == "__main__":
    sys.exit(main())
